// Code generated by counterfeiter. DO NOT EDIT.
package fabproxy

import (
	sync "sync"

	fabproxy "github.com/hyperledger/fabric-chaincode-evm/fabproxy"
	ledger "github.com/hyperledger/fabric-sdk-go/pkg/client/ledger"
	fab "github.com/hyperledger/fabric-sdk-go/pkg/common/providers/fab"
	common "github.com/hyperledger/fabric-sdk-go/third_party/github.com/hyperledger/fabric/protos/common"
	peer "github.com/hyperledger/fabric-sdk-go/third_party/github.com/hyperledger/fabric/protos/peer"
)

type MockLedgerClient struct {
	QueryBlockStub        func(uint64, ...ledger.RequestOption) (*common.Block, error)
	queryBlockMutex       sync.RWMutex
	queryBlockArgsForCall []struct {
		arg1 uint64
		arg2 []ledger.RequestOption
	}
	queryBlockReturns struct {
		result1 *common.Block
		result2 error
	}
	queryBlockReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	QueryBlockByTxIDStub        func(fab.TransactionID, ...ledger.RequestOption) (*common.Block, error)
	queryBlockByTxIDMutex       sync.RWMutex
	queryBlockByTxIDArgsForCall []struct {
		arg1 fab.TransactionID
		arg2 []ledger.RequestOption
	}
	queryBlockByTxIDReturns struct {
		result1 *common.Block
		result2 error
	}
	queryBlockByTxIDReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	QueryInfoStub        func(...ledger.RequestOption) (*fab.BlockchainInfoResponse, error)
	queryInfoMutex       sync.RWMutex
	queryInfoArgsForCall []struct {
		arg1 []ledger.RequestOption
	}
	queryInfoReturns struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}
	queryInfoReturnsOnCall map[int]struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}
	QueryTransactionStub        func(fab.TransactionID, ...ledger.RequestOption) (*peer.ProcessedTransaction, error)
	queryTransactionMutex       sync.RWMutex
	queryTransactionArgsForCall []struct {
		arg1 fab.TransactionID
		arg2 []ledger.RequestOption
	}
	queryTransactionReturns struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}
	queryTransactionReturnsOnCall map[int]struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MockLedgerClient) QueryBlock(arg1 uint64, arg2 ...ledger.RequestOption) (*common.Block, error) {
	fake.queryBlockMutex.Lock()
	ret, specificReturn := fake.queryBlockReturnsOnCall[len(fake.queryBlockArgsForCall)]
	fake.queryBlockArgsForCall = append(fake.queryBlockArgsForCall, struct {
		arg1 uint64
		arg2 []ledger.RequestOption
	}{arg1, arg2})
	fake.recordInvocation("QueryBlock", []interface{}{arg1, arg2})
	fake.queryBlockMutex.Unlock()
	if fake.QueryBlockStub != nil {
		return fake.QueryBlockStub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.queryBlockReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockLedgerClient) QueryBlockCallCount() int {
	fake.queryBlockMutex.RLock()
	defer fake.queryBlockMutex.RUnlock()
	return len(fake.queryBlockArgsForCall)
}

func (fake *MockLedgerClient) QueryBlockCalls(stub func(uint64, ...ledger.RequestOption) (*common.Block, error)) {
	fake.queryBlockMutex.Lock()
	defer fake.queryBlockMutex.Unlock()
	fake.QueryBlockStub = stub
}

func (fake *MockLedgerClient) QueryBlockArgsForCall(i int) (uint64, []ledger.RequestOption) {
	fake.queryBlockMutex.RLock()
	defer fake.queryBlockMutex.RUnlock()
	argsForCall := fake.queryBlockArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockLedgerClient) QueryBlockReturns(result1 *common.Block, result2 error) {
	fake.queryBlockMutex.Lock()
	defer fake.queryBlockMutex.Unlock()
	fake.QueryBlockStub = nil
	fake.queryBlockReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlockReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.queryBlockMutex.Lock()
	defer fake.queryBlockMutex.Unlock()
	fake.QueryBlockStub = nil
	if fake.queryBlockReturnsOnCall == nil {
		fake.queryBlockReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.queryBlockReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlockByTxID(arg1 fab.TransactionID, arg2 ...ledger.RequestOption) (*common.Block, error) {
	fake.queryBlockByTxIDMutex.Lock()
	ret, specificReturn := fake.queryBlockByTxIDReturnsOnCall[len(fake.queryBlockByTxIDArgsForCall)]
	fake.queryBlockByTxIDArgsForCall = append(fake.queryBlockByTxIDArgsForCall, struct {
		arg1 fab.TransactionID
		arg2 []ledger.RequestOption
	}{arg1, arg2})
	fake.recordInvocation("QueryBlockByTxID", []interface{}{arg1, arg2})
	fake.queryBlockByTxIDMutex.Unlock()
	if fake.QueryBlockByTxIDStub != nil {
		return fake.QueryBlockByTxIDStub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.queryBlockByTxIDReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockLedgerClient) QueryBlockByTxIDCallCount() int {
	fake.queryBlockByTxIDMutex.RLock()
	defer fake.queryBlockByTxIDMutex.RUnlock()
	return len(fake.queryBlockByTxIDArgsForCall)
}

func (fake *MockLedgerClient) QueryBlockByTxIDCalls(stub func(fab.TransactionID, ...ledger.RequestOption) (*common.Block, error)) {
	fake.queryBlockByTxIDMutex.Lock()
	defer fake.queryBlockByTxIDMutex.Unlock()
	fake.QueryBlockByTxIDStub = stub
}

func (fake *MockLedgerClient) QueryBlockByTxIDArgsForCall(i int) (fab.TransactionID, []ledger.RequestOption) {
	fake.queryBlockByTxIDMutex.RLock()
	defer fake.queryBlockByTxIDMutex.RUnlock()
	argsForCall := fake.queryBlockByTxIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockLedgerClient) QueryBlockByTxIDReturns(result1 *common.Block, result2 error) {
	fake.queryBlockByTxIDMutex.Lock()
	defer fake.queryBlockByTxIDMutex.Unlock()
	fake.QueryBlockByTxIDStub = nil
	fake.queryBlockByTxIDReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlockByTxIDReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.queryBlockByTxIDMutex.Lock()
	defer fake.queryBlockByTxIDMutex.Unlock()
	fake.QueryBlockByTxIDStub = nil
	if fake.queryBlockByTxIDReturnsOnCall == nil {
		fake.queryBlockByTxIDReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.queryBlockByTxIDReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryInfo(arg1 ...ledger.RequestOption) (*fab.BlockchainInfoResponse, error) {
	fake.queryInfoMutex.Lock()
	ret, specificReturn := fake.queryInfoReturnsOnCall[len(fake.queryInfoArgsForCall)]
	fake.queryInfoArgsForCall = append(fake.queryInfoArgsForCall, struct {
		arg1 []ledger.RequestOption
	}{arg1})
	fake.recordInvocation("QueryInfo", []interface{}{arg1})
	fake.queryInfoMutex.Unlock()
	if fake.QueryInfoStub != nil {
		return fake.QueryInfoStub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.queryInfoReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockLedgerClient) QueryInfoCallCount() int {
	fake.queryInfoMutex.RLock()
	defer fake.queryInfoMutex.RUnlock()
	return len(fake.queryInfoArgsForCall)
}

func (fake *MockLedgerClient) QueryInfoCalls(stub func(...ledger.RequestOption) (*fab.BlockchainInfoResponse, error)) {
	fake.queryInfoMutex.Lock()
	defer fake.queryInfoMutex.Unlock()
	fake.QueryInfoStub = stub
}

func (fake *MockLedgerClient) QueryInfoArgsForCall(i int) []ledger.RequestOption {
	fake.queryInfoMutex.RLock()
	defer fake.queryInfoMutex.RUnlock()
	argsForCall := fake.queryInfoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MockLedgerClient) QueryInfoReturns(result1 *fab.BlockchainInfoResponse, result2 error) {
	fake.queryInfoMutex.Lock()
	defer fake.queryInfoMutex.Unlock()
	fake.QueryInfoStub = nil
	fake.queryInfoReturns = struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryInfoReturnsOnCall(i int, result1 *fab.BlockchainInfoResponse, result2 error) {
	fake.queryInfoMutex.Lock()
	defer fake.queryInfoMutex.Unlock()
	fake.QueryInfoStub = nil
	if fake.queryInfoReturnsOnCall == nil {
		fake.queryInfoReturnsOnCall = make(map[int]struct {
			result1 *fab.BlockchainInfoResponse
			result2 error
		})
	}
	fake.queryInfoReturnsOnCall[i] = struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryTransaction(arg1 fab.TransactionID, arg2 ...ledger.RequestOption) (*peer.ProcessedTransaction, error) {
	fake.queryTransactionMutex.Lock()
	ret, specificReturn := fake.queryTransactionReturnsOnCall[len(fake.queryTransactionArgsForCall)]
	fake.queryTransactionArgsForCall = append(fake.queryTransactionArgsForCall, struct {
		arg1 fab.TransactionID
		arg2 []ledger.RequestOption
	}{arg1, arg2})
	fake.recordInvocation("QueryTransaction", []interface{}{arg1, arg2})
	fake.queryTransactionMutex.Unlock()
	if fake.QueryTransactionStub != nil {
		return fake.QueryTransactionStub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.queryTransactionReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockLedgerClient) QueryTransactionCallCount() int {
	fake.queryTransactionMutex.RLock()
	defer fake.queryTransactionMutex.RUnlock()
	return len(fake.queryTransactionArgsForCall)
}

func (fake *MockLedgerClient) QueryTransactionCalls(stub func(fab.TransactionID, ...ledger.RequestOption) (*peer.ProcessedTransaction, error)) {
	fake.queryTransactionMutex.Lock()
	defer fake.queryTransactionMutex.Unlock()
	fake.QueryTransactionStub = stub
}

func (fake *MockLedgerClient) QueryTransactionArgsForCall(i int) (fab.TransactionID, []ledger.RequestOption) {
	fake.queryTransactionMutex.RLock()
	defer fake.queryTransactionMutex.RUnlock()
	argsForCall := fake.queryTransactionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockLedgerClient) QueryTransactionReturns(result1 *peer.ProcessedTransaction, result2 error) {
	fake.queryTransactionMutex.Lock()
	defer fake.queryTransactionMutex.Unlock()
	fake.QueryTransactionStub = nil
	fake.queryTransactionReturns = struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryTransactionReturnsOnCall(i int, result1 *peer.ProcessedTransaction, result2 error) {
	fake.queryTransactionMutex.Lock()
	defer fake.queryTransactionMutex.Unlock()
	fake.QueryTransactionStub = nil
	if fake.queryTransactionReturnsOnCall == nil {
		fake.queryTransactionReturnsOnCall = make(map[int]struct {
			result1 *peer.ProcessedTransaction
			result2 error
		})
	}
	fake.queryTransactionReturnsOnCall[i] = struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.queryBlockMutex.RLock()
	defer fake.queryBlockMutex.RUnlock()
	fake.queryBlockByTxIDMutex.RLock()
	defer fake.queryBlockByTxIDMutex.RUnlock()
	fake.queryInfoMutex.RLock()
	defer fake.queryInfoMutex.RUnlock()
	fake.queryTransactionMutex.RLock()
	defer fake.queryTransactionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MockLedgerClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fabproxy.LedgerClient = new(MockLedgerClient)
