// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-chaincode-evm/fabproxy"
	"github.com/hyperledger/fabric-sdk-go/pkg/client/ledger"
	"github.com/hyperledger/fabric-sdk-go/pkg/common/providers/fab"
	"github.com/hyperledger/fabric-sdk-go/third_party/github.com/hyperledger/fabric/protos/common"
	"github.com/hyperledger/fabric-sdk-go/third_party/github.com/hyperledger/fabric/protos/peer"
)

type MockLedgerClient struct {
	QueryInfoStub        func(options ...ledger.RequestOption) (*fab.BlockchainInfoResponse, error)
	queryInfoMutex       sync.RWMutex
	queryInfoArgsForCall []struct {
		options []ledger.RequestOption
	}
	queryInfoReturns struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}
	queryInfoReturnsOnCall map[int]struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}
	QueryBlockStub        func(blockNumber uint64, options ...ledger.RequestOption) (*common.Block, error)
	queryBlockMutex       sync.RWMutex
	queryBlockArgsForCall []struct {
		blockNumber uint64
		options     []ledger.RequestOption
	}
	queryBlockReturns struct {
		result1 *common.Block
		result2 error
	}
	queryBlockReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	QueryBlockByTxIDStub        func(txid fab.TransactionID, options ...ledger.RequestOption) (*common.Block, error)
	queryBlockByTxIDMutex       sync.RWMutex
	queryBlockByTxIDArgsForCall []struct {
		txid    fab.TransactionID
		options []ledger.RequestOption
	}
	queryBlockByTxIDReturns struct {
		result1 *common.Block
		result2 error
	}
	queryBlockByTxIDReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	QueryTransactionStub        func(txid fab.TransactionID, options ...ledger.RequestOption) (*peer.ProcessedTransaction, error)
	queryTransactionMutex       sync.RWMutex
	queryTransactionArgsForCall []struct {
		txid    fab.TransactionID
		options []ledger.RequestOption
	}
	queryTransactionReturns struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}
	queryTransactionReturnsOnCall map[int]struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MockLedgerClient) QueryInfo(options ...ledger.RequestOption) (*fab.BlockchainInfoResponse, error) {
	fake.queryInfoMutex.Lock()
	ret, specificReturn := fake.queryInfoReturnsOnCall[len(fake.queryInfoArgsForCall)]
	fake.queryInfoArgsForCall = append(fake.queryInfoArgsForCall, struct {
		options []ledger.RequestOption
	}{options})
	fake.recordInvocation("QueryInfo", []interface{}{options})
	fake.queryInfoMutex.Unlock()
	if fake.QueryInfoStub != nil {
		return fake.QueryInfoStub(options...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.queryInfoReturns.result1, fake.queryInfoReturns.result2
}

func (fake *MockLedgerClient) QueryInfoCallCount() int {
	fake.queryInfoMutex.RLock()
	defer fake.queryInfoMutex.RUnlock()
	return len(fake.queryInfoArgsForCall)
}

func (fake *MockLedgerClient) QueryInfoArgsForCall(i int) []ledger.RequestOption {
	fake.queryInfoMutex.RLock()
	defer fake.queryInfoMutex.RUnlock()
	return fake.queryInfoArgsForCall[i].options
}

func (fake *MockLedgerClient) QueryInfoReturns(result1 *fab.BlockchainInfoResponse, result2 error) {
	fake.QueryInfoStub = nil
	fake.queryInfoReturns = struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryInfoReturnsOnCall(i int, result1 *fab.BlockchainInfoResponse, result2 error) {
	fake.QueryInfoStub = nil
	if fake.queryInfoReturnsOnCall == nil {
		fake.queryInfoReturnsOnCall = make(map[int]struct {
			result1 *fab.BlockchainInfoResponse
			result2 error
		})
	}
	fake.queryInfoReturnsOnCall[i] = struct {
		result1 *fab.BlockchainInfoResponse
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlock(blockNumber uint64, options ...ledger.RequestOption) (*common.Block, error) {
	fake.queryBlockMutex.Lock()
	ret, specificReturn := fake.queryBlockReturnsOnCall[len(fake.queryBlockArgsForCall)]
	fake.queryBlockArgsForCall = append(fake.queryBlockArgsForCall, struct {
		blockNumber uint64
		options     []ledger.RequestOption
	}{blockNumber, options})
	fake.recordInvocation("QueryBlock", []interface{}{blockNumber, options})
	fake.queryBlockMutex.Unlock()
	if fake.QueryBlockStub != nil {
		return fake.QueryBlockStub(blockNumber, options...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.queryBlockReturns.result1, fake.queryBlockReturns.result2
}

func (fake *MockLedgerClient) QueryBlockCallCount() int {
	fake.queryBlockMutex.RLock()
	defer fake.queryBlockMutex.RUnlock()
	return len(fake.queryBlockArgsForCall)
}

func (fake *MockLedgerClient) QueryBlockArgsForCall(i int) (uint64, []ledger.RequestOption) {
	fake.queryBlockMutex.RLock()
	defer fake.queryBlockMutex.RUnlock()
	return fake.queryBlockArgsForCall[i].blockNumber, fake.queryBlockArgsForCall[i].options
}

func (fake *MockLedgerClient) QueryBlockReturns(result1 *common.Block, result2 error) {
	fake.QueryBlockStub = nil
	fake.queryBlockReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlockReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.QueryBlockStub = nil
	if fake.queryBlockReturnsOnCall == nil {
		fake.queryBlockReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.queryBlockReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlockByTxID(txid fab.TransactionID, options ...ledger.RequestOption) (*common.Block, error) {
	fake.queryBlockByTxIDMutex.Lock()
	ret, specificReturn := fake.queryBlockByTxIDReturnsOnCall[len(fake.queryBlockByTxIDArgsForCall)]
	fake.queryBlockByTxIDArgsForCall = append(fake.queryBlockByTxIDArgsForCall, struct {
		txid    fab.TransactionID
		options []ledger.RequestOption
	}{txid, options})
	fake.recordInvocation("QueryBlockByTxID", []interface{}{txid, options})
	fake.queryBlockByTxIDMutex.Unlock()
	if fake.QueryBlockByTxIDStub != nil {
		return fake.QueryBlockByTxIDStub(txid, options...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.queryBlockByTxIDReturns.result1, fake.queryBlockByTxIDReturns.result2
}

func (fake *MockLedgerClient) QueryBlockByTxIDCallCount() int {
	fake.queryBlockByTxIDMutex.RLock()
	defer fake.queryBlockByTxIDMutex.RUnlock()
	return len(fake.queryBlockByTxIDArgsForCall)
}

func (fake *MockLedgerClient) QueryBlockByTxIDArgsForCall(i int) (fab.TransactionID, []ledger.RequestOption) {
	fake.queryBlockByTxIDMutex.RLock()
	defer fake.queryBlockByTxIDMutex.RUnlock()
	return fake.queryBlockByTxIDArgsForCall[i].txid, fake.queryBlockByTxIDArgsForCall[i].options
}

func (fake *MockLedgerClient) QueryBlockByTxIDReturns(result1 *common.Block, result2 error) {
	fake.QueryBlockByTxIDStub = nil
	fake.queryBlockByTxIDReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryBlockByTxIDReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.QueryBlockByTxIDStub = nil
	if fake.queryBlockByTxIDReturnsOnCall == nil {
		fake.queryBlockByTxIDReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.queryBlockByTxIDReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryTransaction(txid fab.TransactionID, options ...ledger.RequestOption) (*peer.ProcessedTransaction, error) {
	fake.queryTransactionMutex.Lock()
	ret, specificReturn := fake.queryTransactionReturnsOnCall[len(fake.queryTransactionArgsForCall)]
	fake.queryTransactionArgsForCall = append(fake.queryTransactionArgsForCall, struct {
		txid    fab.TransactionID
		options []ledger.RequestOption
	}{txid, options})
	fake.recordInvocation("QueryTransaction", []interface{}{txid, options})
	fake.queryTransactionMutex.Unlock()
	if fake.QueryTransactionStub != nil {
		return fake.QueryTransactionStub(txid, options...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.queryTransactionReturns.result1, fake.queryTransactionReturns.result2
}

func (fake *MockLedgerClient) QueryTransactionCallCount() int {
	fake.queryTransactionMutex.RLock()
	defer fake.queryTransactionMutex.RUnlock()
	return len(fake.queryTransactionArgsForCall)
}

func (fake *MockLedgerClient) QueryTransactionArgsForCall(i int) (fab.TransactionID, []ledger.RequestOption) {
	fake.queryTransactionMutex.RLock()
	defer fake.queryTransactionMutex.RUnlock()
	return fake.queryTransactionArgsForCall[i].txid, fake.queryTransactionArgsForCall[i].options
}

func (fake *MockLedgerClient) QueryTransactionReturns(result1 *peer.ProcessedTransaction, result2 error) {
	fake.QueryTransactionStub = nil
	fake.queryTransactionReturns = struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) QueryTransactionReturnsOnCall(i int, result1 *peer.ProcessedTransaction, result2 error) {
	fake.QueryTransactionStub = nil
	if fake.queryTransactionReturnsOnCall == nil {
		fake.queryTransactionReturnsOnCall = make(map[int]struct {
			result1 *peer.ProcessedTransaction
			result2 error
		})
	}
	fake.queryTransactionReturnsOnCall[i] = struct {
		result1 *peer.ProcessedTransaction
		result2 error
	}{result1, result2}
}

func (fake *MockLedgerClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.queryInfoMutex.RLock()
	defer fake.queryInfoMutex.RUnlock()
	fake.queryBlockMutex.RLock()
	defer fake.queryBlockMutex.RUnlock()
	fake.queryBlockByTxIDMutex.RLock()
	defer fake.queryBlockByTxIDMutex.RUnlock()
	fake.queryTransactionMutex.RLock()
	defer fake.queryTransactionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MockLedgerClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fabproxy.LedgerClient = new(MockLedgerClient)
